name: knowledge-stack

services:
  file-api:
    build:
      context: ./file-api
    platform: amd64
    image: file-api:latest
    env_file:
      - .env
    environment:
      REDIS_URL: redis://localhost:6379
      DATABASE_URL: postgresql://knowledge_stack:knowledge_stack@localhost:5432/knowledge_stack
      RUSTFS_URL: http://localhost:9000
      RUSTFS_ACCESS_KEY: minioadmin
      RUSTFS_SECRET_KEY: minioadmin
      RUSTFS_BUCKET_NAME: content-bucket
      STORAGE_PUBLIC_URL: http://localhost:9000
      MILVUS_URI: http://localhost:19530
    volumes:
      - ./file-api:/app
    network_mode: host

  file-worker:
    build:
      context: ./file-worker
    platform: amd64
    image: file-worker:latest
    deploy:
      replicas: 1
    env_file:
      - .env
    environment:
      REDIS_URL: redis://localhost:6379
      DATABASE_URL: postgresql://knowledge_stack:knowledge_stack@localhost:5432/knowledge_stack
      MILVUS_URI: http://localhost:19530
      RUSTFS_URL: http://localhost:9000
      RUSTFS_ACCESS_KEY: minioadmin
      RUSTFS_SECRET_KEY: minioadmin
      RUSTFS_BUCKET_NAME: content-bucket
    volumes:
      - ./file-worker:/app
    depends_on:
      - file-api
    network_mode: host

  ui:
    build:
      context: ./ui
    platform: amd64
    image: file-ui:latest
    depends_on:
      - file-api
    network_mode: host
